Revert "utils/webp: support gif to animated webp"
This reverts commit e392caf91e6f8deb4e68e340fe1e6af610f00efe.

Traceback (most recent call last):
  File "./generate.py", line 137, in <module>
    renderer.render(games, env, language, ui, output)
  File "/home/runner/work/games/games/renderers/game.py", line 97, in render
    f.write(env.get_template("game.html").render(context))
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "templates/game.html", line 37, in top-level template code
    {{ image.dom(rr, i, name, name = get(game, lang, 'name')) }}
  File "/home/runner/work/games/games/utils/image.py", line 111, in dom
    return mode(rr, image_meta, gameid, name)
  File "/home/runner/work/games/games/utils/image.py", line 87, in _media_image
    return '<img alt="%s" src="%s">' % (escape(name), uri(rr, image["uri"], gameid))
  File "/home/runner/work/games/games/utils/image.py", line 78, in uri
    webp.cwebp(path, img.path)
  File "/home/runner/work/games/games/utils/webp.py", line 29, in cwebp
    raise RuntimeError(f"{command}: {ofn} error, outputs:\n{cp.stdout.decode('utf-8')}")
RuntimeError: gif2webp: FGI-nightly-webp/assets/Familiar_Travels/2a24d8f4728b58a33a88df14ef6192eabf371851.gif error, outputs:
GIFLib Error 0: Image EOF detected before image complete